services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate && gunicorn --config gunicorn_config.py src.config.wsgi:application"
    volumes:
      - ./src:/app/src
      - db:/app/db
    ports:
      - "8000:8000"
    environment:
      - DEBUG
      - DJANGO_SECRET_KEY
      - BASE_HOST
      - VIRTUAL_HOST
      - LETSENCRYPT_HOST
      - TELEGRAM_BOT_NAME
      - TELEGRAM_BOT_TOKEN
      - TELEGRAM_LOGIN_REDIRECT_URL

volumes:
  db:
