services:
  web:
    build: .
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - BASE_HOST
      - VIRTUAL_HOST
      - LETSENCRYPT_HOST
      - TELEGRAM_BOT_NAME
      - TELEGRAM_BOT_TOKEN
      - TELEGRAM_LOGIN_REDIRECT_URL