services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn --config gunicorn_config.py config.wsgi:application"
    env_file: .env
    volumes:
      - db:/app/db
      - static_volume:/app/staticfiles
    expose:
      - 8000
    environment:
      - DEBUG
      - DJANGO_SECRET_KEY
      - BASE_HOST
      - TELEGRAM_BOT_NAME
      - TELEGRAM_BOT_TOKEN
      - TELEGRAM_LOGIN_REDIRECT_URL
      - VIRTUAL_HOST=
      - LETSENCRYPT_HOST=
    restart: always
  nginx:
    build: ./nginx
    env_file: .env
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - 80
    ports:
      - ${NGINX_PORT:-}:80
    depends_on:
      - web
    restart: always
  huey_worker:
    build: .
    container_name: huey_worker
    command: python manage.py run_huey
    env_file: .env
    volumes:
      - db:/app/db
    depends_on:
      - web
    environment:
      - VIRTUAL_HOST=
      - LETSENCRYPT_HOST=
    restart: always
volumes:
  db:
    external:
      name: spinnslot_db
  static_volume:
