# Generated by Django 5.1.5 on 2025-02-12 06:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='working_hours_end',
            field=models.TimeField(default='22:00'),
        ),
        migrations.AddField(
            model_name='customers',
            name='working_hours_start',
            field=models.TimeField(default='10:00'),
        ),
        migrations.AlterField(
            model_name='userslot',
            name='reservation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
