# Generated by Django 5.1.5 on 2025-02-28 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_customers_working_hours_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название турнира')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('max_participants', models.PositiveIntegerField(verbose_name='Максимум участников')),
                ('description', models.TextField(verbose_name='Описание')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.customers', verbose_name='Организатор')),
                ('tables', models.ManyToManyField(to='web.itemslot', verbose_name='Используемые столы')),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турниры',
            },
        ),
        migrations.CreateModel(
            name='TournamentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.tournament', verbose_name='Турнир')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Регистрация на турнир',
                'verbose_name_plural': 'Регистрации на турниры',
                'unique_together': {('user', 'tournament')},
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='participants',
            field=models.ManyToManyField(through='web.TournamentRegistration', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
    ]
