# Generated by Django 5.1.5 on 2025-03-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_timeslot_is_booked_tournament_is_canceled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='registration_deadline',
            field=models.DateTimeField(help_text='Автоматически устанавливается за 2 часа до начала', verbose_name='Дедлайн регистрации'),
        ),
    ]
