# Generated by Django 5.1.5 on 2025-03-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_tournament_registration_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='userslot',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
