# Generated by Django 5.1.5 on 2025-03-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_customers_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Завершен'),
        ),
    ]
