# Generated by Django 5.1.5 on 2025-03-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_tournament_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_training',
            field=models.BooleanField(default=False, verbose_name='Тренировка'),
        ),
    ]
