# Generated by Django 5.1.7 on 2025-03-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_tournament_is_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='base_description_tournament',
            field=models.TextField(default='', verbose_name='Базовое описание турнира'),
        ),
        migrations.AddField(
            model_name='customers',
            name='base_description_training',
            field=models.TextField(default='', verbose_name='Базовое описание тренировки'),
        ),
    ]
