# Generated by Django 5.1.7 on 2025-03-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_customers_base_description_tournament_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemslot',
            options={'ordering': ['name'], 'verbose_name': 'ItemSlot', 'verbose_name_plural': 'ItemSlots'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['time_slot'], 'verbose_name': 'TimeSlot', 'verbose_name_plural': 'TimeSlots'},
        ),
    ]
