# Generated by Django 5.1.7 on 2026-03-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20250315_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='vk_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
