# Generated by Django 5.1.7 on 2026-09-30

from django.conf import settings
from django.db import migrations, models


def create_site_configuration(apps, schema_editor):
    SiteConfiguration = apps.get_model('web', 'SiteConfiguration')
    SiteConfiguration.objects.get_or_create(pk=1, defaults={'is_closed': True})


def remove_site_configuration(apps, schema_editor):
    SiteConfiguration = apps.get_model('web', 'SiteConfiguration')
    SiteConfiguration.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_customuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('is_closed', models.BooleanField(default=True, verbose_name='Клуб закрыт')),
                ('closed_title', models.CharField(default='Теннисный клуб закрыт', max_length=200, verbose_name='Заголовок')),
                ('closed_message', models.TextField(default='Друзья, наш теннисный клуб завершил свою работу. Бронирование столов и регистрация на турниры больше недоступны.', verbose_name='Сообщение о закрытии')),
                ('gratitude_message', models.TextField(default='Спасибо организаторам, которые создавали турниры и встречи, и каждому участнику — за игры, эмоции, поддержку и время, проведённое вместе. Это была замечательная история.', verbose_name='Благодарность')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройка сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.RunPython(create_site_configuration, remove_site_configuration),
        migrations.AlterField(
            model_name='tournament',
            name='participants',
            field=models.ManyToManyField(
                through='web.TournamentRegistration',
                through_fields=('tournament', 'user'),
                to=settings.AUTH_USER_MODEL,
                verbose_name='Участники',
            ),
        ),
    ]
